{{- if .Values.overview.enabled }}
apiVersion: templates.krateo.io/v1alpha1
kind: Collection
metadata:
  name: composition-{{ .Release.Name }}-tabpane-overview-row-column-1-panel
  namespace: {{ .Release.Namespace }}
spec:
  type: panel
  widgetsRefs:
  - apiVersion: templates.krateo.io/v1alpha1
    resource: widgets
    name: composition-{{ .Release.Name }}-tabpane-overview-row-column-1-panel-paragraph
    namespace: {{ .Release.Namespace }}
{{- end}}