{{- if .Values.finops.enabled }}
apiVersion: v1
data:
  title: "Optimizations"
kind: ConfigMap
metadata:
  name: composition-{{ .Release.Name }}-tabpane-finops-panel-row-3-column-2-panel
---
apiVersion: templates.krateo.io/v1alpha1
kind: Collection
metadata:
  name: composition-{{ .Release.Name }}-tabpane-finops-panel-row-3-column-2-panel
spec:
  type: panel
  propsRef:
    name: composition-{{ .Release.Name }}-tabpane-finops-panel-row-3-column-2-panel
    namespace: {{ .Release.Namespace }}
  widgetsRefs:
  - apiVersion: templates.krateo.io/v1alpha1
    name: composition-{{ .Release.Name }}-tabpane-finops-panel-row-3-column-2-panel-paragraph
    namespace: {{ .Release.Namespace }}
    resource: widgets
{{- end }}