{{- if .Values.yamlviewer.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: composition-{{ .Release.Name }}-tabpane-yamlviewer
  namespace: {{ .Release.Namespace }}
data:
  label: Values
---
apiVersion: templates.krateo.io/v1alpha1
kind: Collection
metadata:
  name: composition-{{ .Release.Name }}-tabpane-yamlviewer
  namespace: {{ .Release.Namespace }}
spec:
  type: tabpane
  propsRef:
    name: composition-{{ .Release.Name }}-tabpane-yamlviewer
    namespace: {{ .Release.Namespace }}
  widgetsRefs:
  - apiVersion: templates.krateo.io/v1alpha1
    resource: collections
    name: composition-{{ .Release.Name }}-tabpane-yamlviewer-row
    namespace: {{ .Release.Namespace }}
{{- end }}