apiVersion: templates.krateo.io/v1alpha1
kind: Collection
metadata:
  name: composition-{{ .Release.Name }}-tablist
  namespace: {{ .Release.Namespace }}
spec:
  type: tablist
  widgetsRefs:
  - apiVersion: templates.krateo.io/v1alpha1
    resource: collections
    name: composition-{{ .Release.Name }}-tabpane-overview
    namespace: {{ .Release.Namespace }}
  - apiVersion: templates.krateo.io/v1alpha1
    resource: collections
    name: composition-{{ .Release.Name }}-tabpane-compositionstatus
    namespace: {{ .Release.Namespace }}
  - apiVersion: templates.krateo.io/v1alpha1
    resource: collections
    name: composition-{{ .Release.Name }}-tabpane-runs
    namespace: {{ .Release.Namespace }}
  # - apiVersion: templates.krateo.io/v1alpha1
  #   resource: collections
  #   name: composition-{{ .Release.Name }}-tabpane-registration
  #   namespace: {{ .Release.Namespace }}
  # - apiVersion: templates.krateo.io/v1alpha1
  #   resource: collections
  #   name: composition-{{ .Release.Name }}-tabpane-deployment
  #   namespace: {{ .Release.Namespace }}
  - apiVersion: templates.krateo.io/v1alpha1
    resource: collections
    name: composition-{{ .Release.Name }}-tabpane-events
    namespace: {{ .Release.Namespace }}