kind: ConfigMap
apiVersion: v1
metadata:
  name: composition-{{ .Release.Name }}-tabpane-runs-row-column-1-panel-row-column-2
  namespace: {{ .Release.Namespace }}
data:
  width: "16"
---
apiVersion: templates.krateo.io/v1alpha1
kind: Collection
metadata:
  name: composition-{{ .Release.Name }}-tabpane-runs-row-column-1-panel-row-column-2
  namespace: {{ .Release.Namespace }}
spec:
  type: column
  propsRef:
    name: composition-{{ .Release.Name }}-tabpane-runs-row-column-1-panel-row-column-2
    namespace: {{ .Release.Namespace }}
  widgetsRefs:
  - apiVersion: templates.krateo.io/v1alpha1
    resource: widgets
    name: composition-{{ .Release.Name }}-tabpane-runs-row-column-1-panel-row-column-2-customform
    namespace: {{ .Release.Namespace }}