apiVersion: templates.krateo.io/v1alpha1
kind: Collection
metadata:
  name: composition-{{ .Release.Name }}-tabpane-runs-row-column-1-panel
  namespace: {{ .Release.Namespace }}
spec:
  type: panel
  widgetsRefs:
  - apiVersion: templates.krateo.io/v1alpha1
    resource: collections
    name: composition-{{ .Release.Name }}-tabpane-runs-row-column-1-panel-row
    namespace: {{ .Release.Namespace }}