{{- if .Values.finops.enabled }}
apiVersion: templates.krateo.io/v1alpha1
kind: Collection
metadata:
  name: composition-{{ .Release.Name }}-tabpane-finops-panel-row-2-column-1-panel
spec:
  type: panel
  widgetsRefs:
  - apiVersion: templates.krateo.io/v1alpha1
    name: composition-{{ .Release.Name }}-tabpane-finops-panel-row-2-column-1-panel-paragraph
    namespace: {{ .Release.Namespace }}
    resource: widgets
{{- end }}