{{- if .Values.finops.enabled }}
apiVersion: v1
data:
  label: FinOps
kind: ConfigMap
metadata:
  name: composition-{{ .Release.Name }}-tabpane-finops
---
apiVersion: templates.krateo.io/v1alpha1
kind: Collection
metadata:
  name: composition-{{ .Release.Name }}-tabpane-finops
spec:
  propsRef:
    name: composition-{{ .Release.Name }}-tabpane-finops
    namespace: {{ .Release.Namespace }}
  type: tabpane
  widgetsRefs:
  - apiVersion: templates.krateo.io/v1alpha1
    name: composition-{{ .Release.Name }}-tabpane-finops-panel
    namespace: {{ .Release.Namespace }}
    resource: collections
{{- end }}