apiVersion: krateo.io/v1alpha1
kind: Patch
metadata:
  name: composition-{{ .Release.Name }}-{{ .Release.Namespace }}-tabpane-events-row-column-1-panel-eventlist
spec:
  from:
    objectReference:
      apiVersion: templates.krateo.io/v1alpha1
      kind: Widget
      name: composition-{{ .Release.Name }}-{{ .Release.Namespace }}-tabpane-events-row-column-1-panel-eventlist
      namespace: {{ .Release.Namespace }}
    fieldPath: metadata
  to:
    objectReference:
      apiVersion: templates.krateo.io/v1alpha1
      kind: Widget
      name: composition-{{ .Release.Name }}-{{ .Release.Namespace }}-tabpane-events-row-column-1-panel-eventlist
      namespace: {{ .Release.Namespace }}
    fieldPath: spec.api[0].path
    transform: ${ "/events/" + .labels["krateo.io/composition-id"] + "?limit=50" }
