kind: ConfigMap
apiVersion: v1
metadata:
  name: composition-{{ .Release.Name }}-tabpane-events-row-column-1-panel-eventlist
  namespace: {{ .Release.Namespace }}
data:
  asGrid: "false"
  sseEndpoint: /notifications/
  sseTopic: {{ .Values.global.compositionId }}
---
apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  name: composition-{{ .Release.Name }}-tabpane-events-row-column-1-panel-eventlist
  namespace: {{ .Release.Namespace }}
spec:
  type: eventlist
  propsRef:
    name: composition-{{ .Release.Name }}-tabpane-events-row-column-1-panel-eventlist
    namespace: {{ .Release.Namespace }}
  app:
    iterator: .getEvents.items
    template:
      event: ${ . | tostring }
  api:
  - name: getEvents
    path: /events/{{ .Values.global.compositionId }}?limit=50
    verb: GET
    endpointRef:
      name: eventsse-internal-endpoint
      namespace: {{ .Values.namespace }}
    headers:
    - 'Accept: application/json'