{{- if .Values.finops.enabled }}
apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  name: composition-{{ .Release.Name }}-tabpane-finops-panel-row-1-column-1-panel-chartpie
spec:
  type: chartpie
  app:
    template:
      title: ${ .costs.status.title }
      description: ${ .costs.status.description }
      series: >
        ${ "{ \"total\":\"" + (.costs.status.series[0].total | tostring) +
        "\", \"data\": [" +
        ( [ .costs.status.series[0].data[] | "{ \"color\": \"" + .color + "\", \"value\": \"" + (.value | tostring) + "\", \"label\": \"" + .label + "\"}" ] | join(",") ) + "]}" }
  api:
  - name: costs
    path: "/call?apiVersion=templates.krateo.io%2Fv1&resource=restactions&name={{ .Release.Name }}-get-costs&namespace=azure-pricing-system"
    verb: GET
    endpointRef:
      name: snowplow-endpoint
      namespace: krateo-system
    headers:
    - 'Accept: application/json'
---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: {{ .Release.Name }}-get-costs
spec:
  api:
  - name: getComposition
    path: "/apis/composition.krateo.io/v0-1-1/namespaces/{{ .Release.Namespace }}/finopsexamplepricingvmazures/{{ .Release.Name }}"
    verb: GET
    headers:
    - 'Accept: application/json'
  - name: costs
    dependsOn: 
      name: getComposition
    endpointRef: 
      name: finops-database-handler-endpoint
      namespace: krateo-system
    path: "/compute/costs"
    verb: POST
    payload: |
      ${ {table_name: "{{ .Values.global.tableName }}", resource_name: .getComposition.spec.name, resource_group_name: .getComposition.spec.resourceGroupName } }
    headers:
    - 'Accept: application/json'
    - 'Content-Type: application/json'
  filter: .costs
{{- end }}