kind: ConfigMap
apiVersion: v1
metadata:
  name: composition-{{ .Release.Name }}-tabpane-runs-row-column-1-panel-row-column-2-card-customform
  namespace: {{ .Release.Namespace }}
data:
  onSubmitId: submit
  onSubmitVerb: POST
  payloadFormKey: spec
---
apiVersion: templates.krateo.io/v1alpha1
kind: CustomForm
metadata:
  name: composition-{{ .Release.Name }}-tabpane-runs-row-column-1-panel-row-column-2-card-customform
  namespace: {{ .Release.Namespace }}
spec:
  type: customform
  propsRef:
    name: composition-{{ .Release.Name }}-tabpane-runs-row-column-1-panel-row-column-2-card-customform
    namespace: {{ .Release.Namespace }}
  actions:
    - template:
        id: submit
        apiVersion: composition.krateo.io/v0-0-1
        verb: POST
        resource: mlflowruns
        payloadToOverride:
        - name: metadata.name
          value: ${ run_name }
        - name: metadata.namespace
          value: ${ "{{ .Values.global.compositionId }}" }
  app:
    template:
      schema: ${ .getCRD | .spec.versions[] | select(.name == "v0-0-1") | .schema.openAPIV3Schema.properties.spec.properties }
      # propertiesToHide: 
      # - fullnameOverride
      # - git.properties.deletionPolicy
      # - git.properties.fromRepo.properties.branch
      # - git.properties.fromRepo.properties.credentials
      # - git.properties.fromRepo.properties.name
      # - git.properties.fromRepo.properties.org
      # - git.properties.fromRepo.properties.scmUrl
      # - git.properties.insecure
      # - git.properties.toRepo.properties.apiUrl
      # - git.properties.toRepo.properties.branch
      # - git.properties.toRepo.properties.credentials
      # - git.properties.toRepo.properties.deletionPolicy
      # - git.properties.toRepo.properties.initialize
      # - git.properties.toRepo.properties.org
      # - git.properties.toRepo.properties.path
      # - git.properties.toRepo.properties.private
      # - git.properties.toRepo.properties.scmUrl
      # - git.properties.unsupportedCapabilities
      # - mlflow
      # - nameOverride
  api:
  - name: getCRD
    path: "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/mlflowruns.composition.krateo.io"
    verb: GET
    headers:
    - 'Accept: application/json'