{{- if .Values.yamlviewer.enabled }}
apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  name: composition-{{ .Release.Name }}-tabpane-yamlviewer-row-column-1-panel-yamlviewer
  namespace: {{ .Release.Namespace }}
spec:
  type: yamlviewer
  app:
    template:
      json: ${ .getCompositionJSON }
  api:
  - name: getCompositionJSON
    path: "/apis/{{ .Values.global.compositionApiVersion }}/namespaces/{{ .Release.Namespace }}/{{ .Values.global.compositionResource }}/{{ .Release.Name }}"
    verb: GET
{{- end }}