apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  name: composition-{{ .Release.Name }}-tabpane-yamlviewer-row-column-1-panel-yamlviewer
  namespace: {{ .Release.Namespace }}
spec:
  type: paragraph
  app:
    template:
      yaml: {{ .getCompositionYaml }}
  api:
  - name: getCompositionYaml
    path: "/apis/{{ .Values.global.compositionApiVersion }}/namespaces/{{ .Release.Namespace }}/{{ .Values.global.compositionResource }}/{{ .Release.Name }}"
    verb: GET
    headers:
    - 'Accept: application/yaml'