{{- if .Values.finops.enabled }}
apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  name: composition-{{ .Release.Name }}-tabpane-finops-panel-row-1-column-2-panel-chartline
spec:
  type: chartline
  app:
    template:
      lines: ${ .costsbreakdown.status.lines }
      xAxisName: ${ .costsbreakdown.status.xAxisName }
      yAxisName: ${ .costsbreakdown.status.yAxisName }
  api:
  - name: costsbreakdown
    path: "/call?apiVersion=templates.krateo.io%2Fv1&resource=restactions&name=composition-{{ .Release.Name }}-get-costs-breakdown&namespace={{ .Release.Namespace }}"
    verb: GET
    endpointRef:
      name: snowplow-endpoint
      namespace: krateo-system
    headers:
    - 'Accept: application/json'
---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: composition-{{ .Release.Name }}-get-costs-breakdown
spec:
  api:
  - name: getComposition
    path: "/apis/{{ .Values.global.compositionApiVersion }}/namespaces/{{ .Release.Namespace }}/{{ .Values.global.compositionResource }}/{{ .Release.Name }}"
    verb: GET
    headers:
    - 'Accept: application/json'
  - name: costsbreakdown
    dependsOn: 
      name: getComposition
    endpointRef: 
      name: finops-database-handler-endpoint
      namespace: krateo-system
    path: "/compute/costsbreakdown"
    verb: POST
    payload: |
      ${ {table_name: "{{ .Values.global.tableName }}_res", resource_name: .getComposition.spec.name, resource_group_name: .getComposition.spec.resourceGroupName } }
    headers:
    - 'Accept: application/json'
    - 'Content-Type: application/json'
  filter: .costsbreakdown
{{- end }}