{{- if .Values.applicationstatus.enabled }}
apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  annotations:
    "krateo.io/verbose-api": "true"
  name: composition-{{ .Release.Name }}-tabpane-applicationstatus-row-column-1-chartflow
  namespace: {{ .Release.Namespace }}
spec:
  type: chartflow
  app:
    template:
      data: ${ .resourceTree.nodes }
  api:
  - name: resourceTree
    path: "api/v1/applications/{{ .Release.Name }}/resource-tree?namespace={{ .Release.Namespace }}"
    verb: GET
    endpointRef:
      name: argocd-endpoint
      namespace: {{ .Values.namespace }}
    headers:
    - 'Accept: application/json'
{{- end }}