apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  annotations:
    "krateo.io/verbose-api": "true"
  name: composition-{{ .Release.Name }}-tabpane-compositionstatus-row-column-1-chartflow
  namespace: {{ .Release.Namespace }}
spec:
  type: chartflow
  app:
    template:
      data: ${ .resourceTree.status }
  api:
  - name: resourceTree
    path: "/apis/templates.krateo.io/v1alpha1/namespaces/{{ .Release.Namespace }}/resourcetrees/composition-resourcetree-{{ .Release.Name }}"
    verb: GET
    headers:
    - 'Accept: application/json'
