apiVersion: resourcetrees.krateo.io/v1
kind: CompositionReference
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  filters:
    exclude:
    - apiVersion: "templates.krateo.io/v1alpha1"
      resource: "collections"
    - apiVersion: "templates.krateo.io/v1alpha1"
      resource: "widgets"
    - apiVersion: "v1"
      resource: "configmaps"
      name: "^composition-"
  reference:
    apiVersion: {{ .Values.global.compositionApiVersion }}
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    resource: {{ .Values.global.compositionResource }}
---
apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  annotations:
    "krateo.io/verbose-api": "true"
  name: composition-{{ .Release.Name }}-tabpane-compositionstatus-row-column-1-chartflow
  namespace: {{ .Release.Namespace }}
spec:
  type: chartflow
  app:
    template:
      data: ${ .resourceTree.items }
  api:
  - name: resourceTree
    path: "compositions/{{ .Values.global.compositionId }}"
    verb: GET
    endpointRef:
      name: resource-tree-handler-endpoint
      namespace: {{ .Values.namespace }}
    headers:
    - 'Accept: application/json'