apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  name: composition-{{ .Release.Name }}-tabpane-overview-row-column-1-panel-paragraph
  namespace: {{ .Release.Namespace }}
spec:
  type: paragraph
  app:
    template:
      text: "This is a scaffolded MLFlow model"